"""Entry point — Recursive Creator Intelligence System.

Usage:
    python3 main.py                      # one interactive cycle
    python3 main.py --cycles 4 --simulate  # scripted demo (no typing, no keys)
    python3 main.py --metrics            # dashboard only
    python3 main.py --reset              # wipe memory back to cold start
    python3 main.py --offline            # force the deterministic engine

With NVIDIA_API_KEY set (see .env.example), recommendations are generated by
NVIDIA NIM; otherwise the deterministic fallback engine is used so the demo
always works.
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from agents.agent3_strategist import StrategistAgent
from agents.bridges import build_memory_agent, build_research_agent
from agents.contracts import Feedback, Recommendation
from tools.nim_client import NIMClient, load_env

MEMORY_FILES = (
    os.path.join("memory", "knowledge_graph.json"),
    os.path.join("memory", "cycle_history.json"),
    os.path.join("memory", "agent2", "surfaced.json"),
)


def simulated_feedback(rec: Recommendation) -> Feedback:
    """Deterministic creator feedback used by --simulate and the demo script.

    Accepts the top pick, rejects rank 3 with a reason (exercising negative
    learning), defers the rest.
    """
    if rec.rank == 1:
        return Feedback(rec.id, "accepted", "Great fit — starting the outline")
    if rec.rank == 3:
        return Feedback(rec.id, "rejected", "Too opinion-flavored for my audience")
    return Feedback(rec.id, "deferred", "Maybe later")


def build_strategist(offline: bool = False, mock: bool = False) -> StrategistAgent:
    """Wire up the system.

    Real integrations are auto-detected (see agents/bridges.py): Agent 1 via
    SUPABASE_URL/SUPABASE_SERVICE_KEY, Agent 2 via memory/agent2/latest.json
    written by scripts/run_agent2_heartbeat.py. --mock forces the stubs.
    """
    memory, memory_label = build_memory_agent(force_mock=mock)
    research, research_label = build_research_agent(memory, force_mock=mock)
    print(f"  Agent 1: {memory_label}")
    print(f"  Agent 2: {research_label}")
    llm = None if offline else NIMClient()
    if llm is not None and not llm.available:
        print("  (No NVIDIA_API_KEY found — using deterministic fallback engine)")
        llm = None
    return StrategistAgent(memory_agent=memory, research_agent=research, llm=llm)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Recursive Creator Intelligence System")
    parser.add_argument("--cycles", type=int, default=1, help="number of cycles to run")
    parser.add_argument("--simulate", action="store_true",
                        help="use scripted creator feedback (no interactive input)")
    parser.add_argument("--offline", action="store_true",
                        help="skip NVIDIA NIM even if a key is configured")
    parser.add_argument("--mock", action="store_true",
                        help="force the stub agents even when real ones are available")
    parser.add_argument("--metrics", action="store_true",
                        help="show the improvement dashboard and exit")
    parser.add_argument("--reset", action="store_true",
                        help="delete persisted memory (cold start) and exit")
    args = parser.parse_args(argv)

    load_env()

    if args.reset:
        for path in MEMORY_FILES:
            if os.path.exists(path):
                os.remove(path)
                print(f"  removed {path}")
        print("  Memory reset — next run is a cold start.")
        return 0

    strategist = build_strategist(offline=args.offline, mock=args.mock)

    if args.metrics:
        strategist.show_improvement_metrics()
        return 0

    provider = simulated_feedback if args.simulate else None
    for _ in range(max(1, args.cycles)):
        strategist.run_cycle(feedback_provider=provider)

    strategist.show_improvement_metrics()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
